name: flutter_founder_fonts
description: 为 Flutter 应用提供方正黑体等四款免费可商用方正字体
version: 0.0.1
homepage: https://github.com/Dandelight/flutter_founder_fonts

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
